# Generated by Django 4.1 on 2022-12-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='best_odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.CharField(max_length=200)),
                ('second_team', models.CharField(max_length=200)),
                ('third_team', models.CharField(max_length=200)),
                ('fourth_team', models.CharField(max_length=200)),
                ('fifth_team', models.CharField(max_length=200)),
            ],
        ),
    ]
