# Generated by Django 4.1 on 2023-01-05 22:02

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_best_odds_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='best_odds',
            name='fifth_team',
        ),
        migrations.RemoveField(
            model_name='best_odds',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='best_odds',
            name='fourth_team',
        ),
        migrations.RemoveField(
            model_name='best_odds',
            name='second_team',
        ),
        migrations.RemoveField(
            model_name='best_odds',
            name='third_team',
        ),
        migrations.CreateModel(
            name='sure_bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure_bet_image', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('best_odds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.best_odds')),
            ],
        ),
    ]
